### ISSUE TITLE
Onduidelijkheid lecture plan

### ISSUE THREAD

**Issue by titusvh** [HAN-ASD-DT/lecture-plan#1]
@dvberkel in lecture plan staat lesstof vanaf gelopen donderdag die dus niet is gegeven. Nu staat week 3 erbij maar eea lijkt niet op te schuiven. Dus hoe wordt die les ingelopen? Ook moeten we voor dinsdag een kata doen, maar is ook nog niet besproken.
Tot slot: wat is de bedoeling van huiswerk bespreken, zoals de turing machine. Die stond voor dinsdag jl. maar toen is niet op de daadwerkelijke opdrachten ingegaan. Of wordt dat volledig individueel via commentaar via de persoonlijke repo's afgehandeld?

**Comment by dvberkel** [comment]
@titusvh Ik ben het niet eens dat er afgelopen donderdag geen college was. Het college was alleen in Amsterdam. Wees niet bang, wat daar vertelt is zal in een andere vorm, herhaald worden door het vak heen.

Het maken van de opgaven is een onderdeel van de slagings criteria van het vak. Je hoeft niet alle opgaven te maken. Hoe meer jij er wel maakt hoe beter er voor dat onderdeel wordt gescoord.

Dinsdag ben ik in gegaan op hoe je een opgave kunt maken omdat sommige mensen hebben aangegeven nog wat extra tijd te willen hebben voor deze opgave.

Wanneer jij een cijfer wilt voor het onderdeel "opgave maken" dan verzoek jij in een ticket om een audit. Ik ga dan kijken naar jou bewijslast en beoordeel aan de hand daarvan het cijfer op dat moment.

**Comment by titusvh** [comment]
@dvberkel 
Ik heb hierboven alleen maar uitspraak gedaan over dat de geplande **lesstof** niet is gegeven: kata's, pair- en mobprogramming (jouw praatje ging volgens het programma heel ergens anders over toch?) . En dat ik verwacht had dat die door zou schuiven. 

Er staat ook huiswerk voor dinsdag gepland obv die lesstof. 

Over uitstel van behandeling huiswerk:  ik heb me ook de tering gehaast de opgave af te krijgen, in mijn lunchpauze op de dag zelf. Ikzelf vind het dan ook wel prettig als er enige consistentie is, en een soort afspraak=afspraak. In het vorige semester werden de mensen die zich wel aan de "afspraken hielden" ook benadeeld door de mensen die huiswerk structureel niet maakten. Ikzelf krijg ook wel 's iets niet af maar dan wordt de stof ook gewoon behandeld en kan ik ervoor kiezen dat deel vd les niet "mee te kijken" als ik denk dat ik er meer van leer als ik het eerst zelf probeer. Maar vandaar mijn serieuze vraag, of het misschien niet eens de bedoeling is de uitwerkingen plenair te behandelen.

Want eerlijk gezegd zijn er bij mij nog veel vragen. En is het mij niet duidelijk wat er nog op ons afkomt en wat de beoordelingscriteria e.d. zijn. Ook hier zou m.i. dinsdag jl. duidelijkheid over komen toen we daar de donderdag ervoor naar vroegen.

Of heb ik wat gemist en staat bv onderdeel "opgave maken" al wél ergens?

**Comment by dvberkel** [comment]
@titusvh De lesstof is wel behandeld. De aankondiging spreekt over deliberate practice en hoe dat als een software ontwikkelaar te doen. Kata's zoals in de verschillende vormen genoemd in de lesstof zijn daar een manier voor.
Het huiswerk wat daarbij past hoort uitgesmeerd te worden over een grotere periode. Het herhalende karakter is namelijk een essentieel onderdeel van het doen van kata's. En dat is iets wat wel ook in het lesplan opgeschoven is, en waar vaker aandacht aan wordt besteed.

Vervelend dat jij haast hebt gemaakt om de opgave af te krijgen. Ik hoop dat jij aan jezelf en jouw grenzen blijft denken. Dat jij aangeeft dat er voor jou te weinig tijd is om een opgave te maken.

De opgave zoals die tot nu toe zijn aangeboden hebben expliciet geen deadline. Ze zijn er om de stof die behandeld is te verdiepen, dat kan ook op een later moment. Ik kan niet in jouw agenda kijken of bepalen hoe jij jouw tijd in wilt delen. Het is daarmee aan de student om te beslissen wanneer de opgave te maken. Omdat er geen deadline is, is er ook geen uitstel.

Omdat ik van mening ben dat het bijdraagt aan de verdieping om opgave te maken, is er een onderdeel "het maken van opgave" waarop een student op wordt beoordeeld. Dit is echter een beoordeling van alle opgave; heb jij voldoende van de individuele opgaven gemaakt.

Merk op dat ik de het maken van een Turing Machine wel heb behandeld. Ik heb een soortgelijke , niet opgegeven, opdracht uitgewerkt. Ik heb die uitgewerkt zoals ik ook een van de opgegeven opdrachten zou uitwerken.
Ik heb hierbij in mijn eigen niemand benadeeld. De mensen die de opgave wel hebben gemaakt hebben kunnen controleren of zij dat juist hebben gedaan. De mensen die de opgave nog niet hebben gemaakt en dat wel willen doen hebben geen gratis oplossing gekregen.

Ik snap dat er nog veel onduidelijk voor jou is. Het nadeel van de opsplitsing van de lessen in video conferencing en een klassikaal deel is dat de interactie via video conferencing anders is. Daarom vond ik het niet zo geschikt om de criteria te presenteren omdat dan moeilijk te proeven is hoe dat valt.
Dat de klassikale les toevallig anders uitviel is ongelukkig, maar geen ramp.
Mijn plan is omdat donderdag klassikaal te behandelen.

Ik hoop echter dat ik jouw zorgen deels kan wegnemen door de volgende opmerking. Jij bent een goede student, die zijn eigen opleiding serieus neemt. Dat laat jij op allerlei manieren zien. Jij bent kritisch, durft vragen te stelen, maakt met aandacht het huiswerk, helpt anderen, maakt verbeteringen aan de stof.
Als jij dat vol houd, en zoals ik jou ken zal jij dat doen, dan is er geen twijfel over dat jij dit vak gaat halen.

**Comment by titusvh** [comment]
Ik had de aankondiging opd e website  "the Four Rules of Simple Design, and the lessons it provides" inderdaad niet mentaal gemapt naar mob/pair programming en kata's.
Maar donderdag komt er meer duidelijkheid, da's fijn en hebben het hier dan wel verder over.
