### ISSUE TITLE
Week 9 - Talks

### ISSUE THREAD

**Issue by Dewinster** [HAN-ASD-DT/lecture-plan#2]
On the lecture plan at week 9 it says that we have an student talk, but according to [https://github.com/HAN-ASD-DT/Talks-Schedule](https://github.com/HAN-ASD-DT/Talks-Schedule) the first talk is 8th of November and week 9 is 1st of November.

**Comment by dvberkel** [comment]
That doesn't mean that the space is not open for a student talk.

Besides, aren't we all students of life :-)
